### ISSUE TITLE
AFR input changed

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB2-issues#35]
from Rev D to E, the input for AFR has changed which causes a conflict in the yaml.  

Rev D-
    Pin- 4w
    Input- IN_O2S
    STM- PA0

Rev E-
    Pin- 4w
    Input- IN_SENS1
    STM- PF3

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/wiki/module-input says that IN_SENS1 is NOT an analog input

**Comment by BeerMoneyMotorsports** [comment]
3L is not present on the OEM harness.  We use the factory front o2 input wire, 4W, for wideband.  This is a common industry practice for the pnp setups.  

All the hellens using external sensor are wired to the factory o2 input wire.

**Comment by andreika-git** [comment]
I need Andrey's @rusefillc help for this one. Since the first rev.A, he told me that 3L should be used for AFR, and not OEM, because adding a new pin is better that cutting the existing OEM harness.

I can return 3L back to life as it was in rev.D but in that case we would have a new problem with IN_TPS2 (needed by ETB). We would need to find a free ADC channel for TPS2.

**Comment by BeerMoneyMotorsports** [comment]
![image](https://user-images.githubusercontent.com/82395131/168892674-90e866d2-0e88-4bcc-a5d5-c9d8c22f872c.png)

**Comment by andreika-git** [comment]
What's the default configuration of these jumpers? Which one is DNP?

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/168976472-6db5f887-6bed-4239-8b9e-aef14dfb0761.png)

**Comment by BeerMoneyMotorsports** [comment]
DNP r39
Place r38

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git do you need anything more from my end before creating the new files?

**Comment by BeerMoneyMotorsports** [comment]
fixed with F
